import { InMemoryDbService } from 'angular-in-memory-web-api';
import { Injectable } from '@angular/core';

@Injectable({
    providedIn: 'root',
})
export class InMemoryDataService implements InMemoryDbService {
    createDb() {
        const employees = [
            {
                id: 1,
                username: 'jdoe',
                firstName: 'John',
                lastName: 'Doe',
                email: 'jdoe@example.com',
                birthDate: 'Fri Jul 19 2024 00:00:00 GMT+0700 (Indochina Time)',
                basicSalary: 50000,
                status: 'Active',
                group: 'IT',
                description: new Date('1990-02-02'),
            },
            {
                id: 2,
                username: 'asmith',
                firstName: 'Anna',
                lastName: 'Smith',
                email: 'asmith@example.com',
                birthDate: 'Fri Jul 19 2024 00:00:00 GMT+0700 (Indochina Time)',
                basicSalary: 60000,
                status: 'Active',
                group: 'IT',
                description: new Date('1990-02-02'),
            },
            // {
            //   id: 3,
            //   username: 'bwilliams',
            //   firstName: 'Bob',
            //   lastName: 'Williams',
            //   email: 'bwilliams@example.com',
            //   birthDate: new Date('1985-03-03'),
            //   basicSalary: 70000,
            //   status: 'inactive',
            //   group: 'A',
            //   description: new Date('1990-02-02'),
            // },
            // {
            //   id: 4,
            //   username: 'cjohnson',
            //   firstName: 'Carol',
            //   lastName: 'Johnson',
            //   email: 'cjohnson@example.com',
            //   birthDate: new Date('1975-04-04'),
            //   basicSalary: 80000,
            //   status: 'active',
            //   group: 'C',
            //   description: new Date('1990-02-02'),
            // },
            // {
            //   id: 5,
            //   username: 'dlee',
            //   firstName: 'David',
            //   lastName: 'Lee',
            //   email: 'dlee@example.com',
            //   birthDate: new Date('1995-05-05'),
            //   basicSalary: 90000,
            //   status: 'inactive',
            //   group: 'B',
            //   description: new Date('1990-02-02'),
            // },
            // {
            //   id: 6,
            //   username: 'emartinez',
            //   firstName: 'Eva',
            //   lastName: 'Martinez',
            //   email: 'emartinez@example.com',
            //   birthDate: new Date('1988-06-06'),
            //   basicSalary: 55000,
            //   status: 'active',
            //   group: 'A',
            //   description: new Date('1990-02-02'),
            // },
            // {
            //   id: 7,
            //   username: 'ffernandez',
            //   firstName: 'Frank',
            //   lastName: 'Fernandez',
            //   email: 'ffernandez@example.com',
            //   birthDate: new Date('1992-07-07'),
            //   basicSalary: 65000,
            //   status: 'active',
            //   group: 'C',
            //   description: new Date('1990-02-02'),
            // },
            // {
            //   id: 8,
            //   username: 'gwalker',
            //   firstName: 'Grace',
            //   lastName: 'Walker',
            //   email: 'gwalker@example.com',
            //   birthDate: new Date('1983-08-08'),
            //   basicSalary: 75000,
            //   status: 'inactive',
            //   group: 'B',
            //   description: new Date('1990-02-02'),
            // },
            // {
            //   id: 9,
            //   username: 'hhernandez',
            //   firstName: 'Henry',
            //   lastName: 'Hernandez',
            //   email: 'hhernandez@example.com',
            //   birthDate: new Date('1978-09-09'),
            //   basicSalary: 85000,
            //   status: 'active',
            //   group: 'C',
            //   description: new Date('1990-02-02'),
            // },
            // {
            //   id: 10,
            //   username: 'ijones',
            //   firstName: 'Ivy',
            //   lastName: 'Jones',
            //   email: 'ijones@example.com',
            //   birthDate: new Date('1991-10-10'),
            //   basicSalary: 95000,
            //   status: 'inactive',
            //   group: 'A',
            //   description: new Date('1990-02-02'),
            // },
            // {
            //   id: 11,
            //   username: 'kking',
            //   firstName: 'Karl',
            //   lastName: 'King',
            //   email: 'kking@example.com',
            //   birthDate: new Date('1984-11-11'),
            //   basicSalary: 60000,
            //   status: 'active',
            //   group: 'A',
            //   description: new Date('1990-02-02'),
            // },
            // {
            //   id: 12,
            //   username: 'lmoore',
            //   firstName: 'Linda',
            //   lastName: 'Moore',
            //   email: 'lmoore@example.com',
            //   birthDate: new Date('1979-12-12'),
            //   basicSalary: 65000,
            //   status: 'inactive',
            //   group: 'B',
            //   description: new Date('1990-02-02'),
            // },
            // {
            //   id: 13,
            //   username: 'nmartin',
            //   firstName: 'Nina',
            //   lastName: 'Martin',
            //   email: 'nmartin@example.com',
            //   birthDate: new Date('1981-01-13'),
            //   basicSalary: 70000,
            //   status: 'active',
            //   group: 'C',
            //   description: new Date('1990-02-02'),
            // },
            // {
            //   id: 14,
            //   username: 'operez',
            //   firstName: 'Oscar',
            //   lastName: 'Perez',
            //   email: 'operez@example.com',
            //   birthDate: new Date('1987-02-14'),
            //   basicSalary: 75000,
            //   status: 'inactive',
            //   group: 'A',
            //   description: new Date('1990-02-02'),
            // },
            // {
            //   id: 15,
            //   username: 'qwhite',
            //   firstName: 'Quincy',
            //   lastName: 'White',
            //   email: 'qwhite@example.com',
            //   birthDate: new Date('1989-03-15'),
            //   basicSalary: 80000,
            //   status: 'active',
            //   group: 'B',
            //   description: new Date('1990-02-02'),
            // },
            // {
            //   id: 16,
            //   username: 'rrivera',
            //   firstName: 'Rachel',
            //   lastName: 'Rivera',
            //   email: 'rrivera@example.com',
            //   birthDate: new Date('1986-04-16'),
            //   basicSalary: 85000,
            //   status: 'inactive',
            //   group: 'C',
            //   description: new Date('1990-02-02'),
            // },
            // {
            //   id: 17,
            //   username: 'sroberts',
            //   firstName: 'Sam',
            //   lastName: 'Roberts',
            //   email: 'sroberts@example.com',
            //   birthDate: new Date('1993-05-17'),
            //   basicSalary: 90000,
            //   status: 'active',
            //   group: 'A',
            //   description: new Date('1990-02-02'),
            // },
            // {
            //   id: 18,
            //   username: 'thall',
            //   firstName: 'Tina',
            //   lastName: 'Hall',
            //   email: 'thall@example.com',
            //   birthDate: new Date('1992-06-18'),
            //   basicSalary: 55000,
            //   status: 'inactive',
            //   group: 'B',
            //   description: new Date('1990-02-02'),
            // },
            // {
            //   id: 19,
            //   username: 'uwright',
            //   firstName: 'Uma',
            //   lastName: 'Wright',
            //   email: 'uwright@example.com',
            //   birthDate: new Date('1982-07-19'),
            //   basicSalary: 60000,
            //   status: 'active',
            //   group: 'C',
            //   description: new Date('1990-02-02'),
            // },
            // {
            //   id: 20,
            //   username: 'vgarcia',
            //   firstName: 'Victor',
            //   lastName: 'Garcia',
            //   email: 'vgarcia@example.com',
            //   birthDate: new Date('1994-08-20'),
            //   basicSalary: 65000,
            //   status: 'inactive',
            //   group: 'A',
            //   description: new Date('1990-02-02'),
            // },
            // {
            //   id: 21,
            //   username: 'wlopez',
            //   firstName: 'Wendy',
            //   lastName: 'Lopez',
            //   email: 'wlopez@example.com',
            //   birthDate: new Date('1990-09-21'),
            //   basicSalary: 70000,
            //   status: 'active',
            //   group: 'B',
            //   description: new Date('1990-02-02'),
            // },
            // {
            //   id: 22,
            //   username: 'xmartinez',
            //   firstName: 'Xander',
            //   lastName: 'Martinez',
            //   email: 'xmartinez@example.com',
            //   birthDate: new Date('1983-10-22'),
            //   basicSalary: 75000,
            //   status: 'inactive',
            //   group: 'C',
            //   description: new Date('1990-02-02'),
            // },
            // {
            //   id: 23,
            //   username: 'ygomez',
            //   firstName: 'Yvonne',
            //   lastName: 'Gomez',
            //   email: 'ygomez@example.com',
            //   birthDate: new Date('1976-11-23'),
            //   basicSalary: 80000,
            //   status: 'active',
            // },
        ];
        return {
            employees,
        };
    }
}
